version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    build: ./nginx
    ports:
      ### NGINX_HOST_HTTP_PORT
      - "80:80"
      ### NGINX_HOST_HTTPS_PORT
      - "443:443"
    depends_on:
      - php-fpm
    volumes:
      # Volume đến code ứng dụng, giống bên php-fpm nữa
      - ./src:/var/www/html/
      - ./nginx/sites:/etc/nginx/sites-available
      - ./mginx/ssl:/etc/nginx/ssl
      # Logging
      - ./nginx/log:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
    networks:
      laravel_docker_net:
        ipv4_address: 172.21.0.2
  mysql:
    container_name: laravel-mysql57
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: '1'
    volumes:
      - /var/lib/mysql57:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      laravel_docker_net:
        ipv4_address: 172.21.0.4
  # adminer:
  #   container_name: laravel-adminer
  #   image: adminer
  #   ports:
  #     - 8081:8080
  php-fpm:
    container_name: laravel-php72
    build: ./php
    image: php:7.2-fpm
    volumes:
      - ./src:/var/www/html/
      - ./php/config/php7.2.ini:/usr/local/etc/php/php.ini
    networks:
      laravel_docker_net:
        ipv4_address: 172.21.0.3
networks:
  laravel_docker_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.0.0/24
